### ISSUE TITLE
Fails to compile for some non-AVR targets (e.g. ESP8266)

### ISSUE THREAD

**Issue by jwende** [vicatcu/BME680_Breakout#2]
It goes down to BME680_Library::i2c_read and the usage of the I2C read methods from <Wire.h>.
The length field is defined as uint16_t but <Wire.h> is using a signature with uint8_t. 
I did a cast to uint8_t - but I guess it isn't a good idea.

  Wire.beginTransmission(dev_id);                          // START+SLA+W
  Wire.write(reg_addr);                                    // REG
  Wire.endTransmission(false);                             // STOP (false would be REP START)
  Wire.requestFrom(dev_id, (uint8_t)len,  1U);                      // SLA+R and STOP

**Comment by skaringa** [comment]
Same issue here. Regarding to the documentation of Wire.requestFrom at https://www.arduino.cc/en/Reference/WireRequestFrom the last parameter is a boolean. So I patched the code this way:

    Wire.beginTransmission(dev_id);  // START+SLA+W
    Wire.write(reg_addr);  // REG
    Wire.endTransmission(false);  // STOP (false would be REP START)
    Wire.requestFrom(dev_id, (size_t)len, true); // SLA+R and STOP

**Comment by vicatcu** [comment]
@skaringa is this true in a fresh checkout of the repository for you? What Tools => Board target are you using. If I make the change you are suggesting it fails to compile for AVR.

```
/home/vic/sketchbook/libraries/BME680_Library/src/BME680_Library.cpp: In static member function 'static int8_t BME680_Library::i2c_read(uint8_t, uint8_t, uint8_t*, uint16_t)':
/home/vic/sketchbook/libraries/BME680_Library/src/BME680_Library.cpp:129:45: error: call of overloaded 'requestFrom(uint8_t&, uint16_t, bool)' is ambiguous
  Wire.requestFrom(dev_id, (size_t) len, true);            // SLA+R and STOP
                                             ^
/home/vic/sketchbook/libraries/BME680_Library/src/BME680_Library.cpp:129:45: note: candidates are:
In file included from /home/vic/sketchbook/libraries/BME680_Library/src/BME680_Library.cpp:3:0:
/home/vic/arduino-1.6.11/hardware/arduino/avr/libraries/Wire/src/Wire.h:62:13: note: uint8_t TwoWire::requestFrom(uint8_t, uint8_t, uint8_t)
     uint8_t requestFrom(uint8_t, uint8_t, uint8_t);
             ^
/home/vic/arduino-1.6.11/hardware/arduino/avr/libraries/Wire/src/Wire.h:65:13: note: uint8_t TwoWire::requestFrom(int, int, int)
     uint8_t requestFrom(int, int, int);
```

I see that the opposite is true for an ESP8266 target. Is there a way to change it to satisfy both targets at the same time (without using a #define ideally)?

**Comment by vicatcu** [comment]
@skaringa Looking it up, AVR's Wire implementation has [these variants](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/libraries/Wire/src/Wire.h#L61-L65) of requestFrom:
 ```c
    uint8_t requestFrom(uint8_t, uint8_t);
    uint8_t requestFrom(uint8_t, uint8_t, uint8_t);
    uint8_t requestFrom(uint8_t, uint8_t, uint32_t, uint8_t, uint8_t);
    uint8_t requestFrom(int, int);
    uint8_t requestFrom(int, int, int);
```

... and ESP8266 has [these variants](https://github.com/esp8266/Arduino/blob/master/libraries/Wire/Wire.h#L64-L70):

```c
    size_t requestFrom(uint8_t address, size_t size, bool sendStop);
    uint8_t requestFrom(uint8_t, uint8_t);
    uint8_t requestFrom(uint8_t, uint8_t, uint8_t);
    uint8_t requestFrom(int, int);
    uint8_t requestFrom(int, int, int);
```

The one we _want_ to have invoked is:
```c
uint8_t requestFrom(uint8_t address, uint8_t quantity, uint8_t sendStop) // AVR
size_t requestFrom(uint8_t address, size_t size, bool sendStop); // ESP8266
```

If I cast all three arguments to (int) it seems to compile for both platforms...

**Comment by vicatcu** [comment]
@jwende @skaringa I just pushed this change, please give it a try and let me know if it works for you, then I'll close this issue.

**Comment by skaringa** [comment]
You are right, I'm using the library on esp8266!
The actual commit casting all three arguments to (int) works well.
Since the code is working on esp8266 now, you may add this architecture to library.properties:
`architectures=avr,esp8266`
Thank you very much!

**Comment by vicatcu** [comment]
@skaringa cool, I've added it, thanks for helping out!
