### ISSUE TITLE
Strange values received from breakout board.

### ISSUE THREAD

**Issue by windkh** [vicatcu/BME680_Breakout#3]
After running the example
(https://github.com/vicatcu/BME680_Breakout/tree/master/BME680_Library/examples/Basic/Basic.ino) 
I am always receiving the same values. In addition to that the values seem to be incorrect:

`Opening port
Port open
BME Initialization...Succeeded!
Configuring Forced Mode...Succeeded!
Temperature(degC),Relative_Humidity(%),Pressure(hPa),Gas_Resistance(Ohms)
33.71,100.00,690.56,0
33.71,100.00,690.56,0
33.71,100.00,690.56,0
33.71,100.00,690.56,0
33.71,100.00,690.56,0
33.71,100.00,690.56,0
33.71,100.00,690.56,0
33.71,100.00,690.56,0
`

The hardware (http://www.watterott.com/de/BME680-Breakout) was attached to an Arduino Uno using 3.3V as VCC.

Any suggestions?
Thanks in advance.

**Comment by BST-Github-Admin** [comment]
@windkh ,

There seems to be a bug in the library. We have reported an issue to the author. You can track the issue.
https://github.com/vicatcu/BME680_Breakout/issues/4

**Comment by windkh** [comment]
Ok thanks. The following lib seems to work
https://github.com/DFRobot/DFRobot_BME680

**Comment by windkh** [comment]
I created a pull request with changed i2c write and read functions.
