### ISSUE TITLE
getGasResistance sometimes returns very low values (<100Ohm)

### ISSUE THREAD

**Issue by windkh** [vicatcu/BME680_Breakout#6]
Comparing the values of a MQ-135 sensor with the values returned from a BME680 I noticed that the library for the BME680 sometimes returns very low values for the gas resistance. Very low means below 100 instead of the expected value of around 15000.

The green line of the following graph is the BME680 while the blue one comes from the MQ-135:
<img width="542" alt="bme680" src="https://user-images.githubusercontent.com/10910767/32292542-c55b9470-bf40-11e7-91b8-a8f871f39a52.png">
The graph shows values of the last 6 hours

Here are some lines from the log file:

2017-11-01_19:51:08 MYSENSOR_BME680_R 14476 Ohm
2017-11-01_19:51:19 MYSENSOR_BME680_T 27.1 °
2017-11-01_19:51:19 MYSENSOR_BME680_R 14396 Ohm
2017-11-01_19:51:30 MYSENSOR_BME680_P 1020.8 mbar
2017-11-01_19:51:40 MYSENSOR_BME680_H 36.7 %
2017-11-01_19:51:40 MYSENSOR_BME680_R 14456 Ohm
**2017-11-01_19:51:51 MYSENSOR_BME680_R 26 Ohm**
2017-11-01_19:52:01 MYSENSOR_BME680_R 14456 Ohm
2017-11-01_19:52:12 MYSENSOR_BME680_H 36.6 %
2017-11-01_19:52:12 MYSENSOR_BME680_R 14416 Ohm
2017-11-01_19:52:44 MYSENSOR_BME680_R 14486 Ohm
2017-11-01_19:52:54 MYSENSOR_BME680_H 36.7 %
2017-11-01_19:52:54 MYSENSOR_BME680_R 14476 Ohm
2017-11-01_19:53:18 MYSENSOR_BME680_R 14426 Ohm
2017-11-01_19:53:29 MYSENSOR_BME680_R 14104 Ohm
2017-11-01_19:53:39 MYSENSOR_BME680_H 36.6 %
2017-11-01_19:53:39 MYSENSOR_BME680_R 14171 Ohm
2017-11-01_19:53:50 MYSENSOR_BME680_H 36.7 %
2017-11-01_19:53:50 MYSENSOR_BME680_R 14258 Ohm
2017-11-01_19:54:00 MYSENSOR_BME680_H 36.8 %
2017-11-01_19:54:01 MYSENSOR_BME680_R 14287 Ohm

The sensor takes a measurement every 10 seconds.

**Comment by vicatcu** [comment]
Interesting, seems like something the devs at https://github.com/BoschSensortec/BME680_driver might have some insight into. This library basically just exposes that library for the Arduino environment. I suppose it _could_ be a numerical issue in the porting, but it might also be a fundamental behavioral issue with the sensor. Would you mind cross-posting the issue to them?

**Comment by windkh** [comment]
No not at all, feel free.
Are the driver files in your lib the latest ones from Bosch?

**Comment by vicatcu** [comment]
@windkh I haven't synchronized with the Bosch repo since Jul 20 at least (looking at the commit log). It's not _quite_ as simple as copy pasting their files into the src/utility folder, but you can do a diff to see if anything jumps out at you and let me know?

**Comment by windkh** [comment]
So you are not just taking a copy of their files? Why not? 
Well the original driver files were not updated for 4 months either, so maybe you are already using the 3.5.1 version.

**Comment by windkh** [comment]
Well, I just compared the files and found only one small block added to one of the headers, the rest is identical. So I think everything should be ok so far.

#if defined(ARDUINO_ARCH_AVR)
	#define UINT8_C(v) ((uint8_t) v)
	#define INT8_C(v) ((int8_t) v)
	#define UINT16_C(v) ((uint16_t) v)
	#define INT16_C(v) ((int16_t) v)
	#define UINT32_C(v) ((uint32_t) v)
	#define INT32_C(v) ((int32_t) v)
	#include <stdint.h>
#endif

**Comment by windkh** [comment]
Running the test over the night showed even negative values like -32768 and even one large negative number -21.........0000. 

Maybe it is a problem mit converting to float on the arduino as the gas resistance value is uint32. I changed the sketch to eliminate the negative values. Let's hope the low values will vanish, too.

**Comment by vicatcu** [comment]
-32768 is interesting insofar as it is -2^15 (which is the most negative represent-able 16-bit 2's complement integer value)... are you just running the Basic example sketch. What is the code that is printing negative values?

**Comment by windkh** [comment]
The code looked like:
float gasResistance = bme680.getGasResistance();
which was definately wrong. Right now I am testing with 
uint32_t gasResistance = bme680.getGasResistance();
which looks better. So far no errors... I keep you informed.

**Comment by windkh** [comment]
Hi, I think there is no problem with your library. Debug logs were ok.
Sorry for false alarm.
